name: im_rich
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - android/
    - android/app/
    - android/app/src/
    - android/app/src/main/
    - android/app/src/main/res/
    - android/app/src/main/res/values/
    - android/app/src/main/res/drawable/
    - android/app/src/main/res/mipmap-hdpi/
    - android/app/src/main/res/mipmap-mdpi/
    - android/app/src/main/res/drawable-v21/
    - android/app/src/main/res/mipmap-xhdpi/
    - android/app/src/main/res/values-night/
    - android/app/src/main/res/mipmap-xxhdpi/
    - android/app/src/main/res/mipmap-xxxhdpi/
    - android/app/src/main/java/
    - android/app/src/main/java/io/
    - android/app/src/main/java/io/flutter/
    - android/app/src/main/java/io/flutter/plugins/
    - android/app/src/main/kotlin/
    - android/app/src/main/kotlin/com/
    - android/app/src/main/kotlin/com/example/
    - android/app/src/main/kotlin/com/example/im_rich/
    - android/app/src/debug/
    - android/app/src/profile/
    - android/app/.cxx/
    - android/app/.cxx/Debug/
    - android/app/.cxx/Debug/1l3o35x2/
    - android/app/.cxx/Debug/1l3o35x2/x86/
    - android/app/.cxx/Debug/1l3o35x2/x86/.cmake/
    - android/app/.cxx/Debug/1l3o35x2/x86/.cmake/api/
    - android/app/.cxx/Debug/1l3o35x2/x86/.cmake/api/v1/
    - android/app/.cxx/Debug/1l3o35x2/x86/.cmake/api/v1/query/
    - android/app/.cxx/Debug/1l3o35x2/x86/.cmake/api/v1/query/client-agp/
    - android/app/.cxx/Debug/1l3o35x2/x86/.cmake/api/v1/reply/
    - android/app/.cxx/Debug/1l3o35x2/x86/CMakeFiles/
    - android/app/.cxx/Debug/1l3o35x2/x86/CMakeFiles/CMakeTmp/
    - android/app/.cxx/Debug/1l3o35x2/x86/CMakeFiles/3.22.1-g37088a8-dirty/
    - android/app/.cxx/Debug/1l3o35x2/x86/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdC/
    - android/app/.cxx/Debug/1l3o35x2/x86/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdC/tmp/
    - android/app/.cxx/Debug/1l3o35x2/x86/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdCXX/
    - android/app/.cxx/Debug/1l3o35x2/x86/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdCXX/tmp/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/.cmake/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/.cmake/api/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/.cmake/api/v1/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/.cmake/api/v1/query/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/.cmake/api/v1/query/client-agp/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/.cmake/api/v1/reply/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/CMakeFiles/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/CMakeFiles/CMakeTmp/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/CMakeFiles/3.22.1-g37088a8-dirty/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdC/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdC/tmp/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdCXX/
    - android/app/.cxx/Debug/1l3o35x2/x86_64/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdCXX/tmp/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/.cmake/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/.cmake/api/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/.cmake/api/v1/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/.cmake/api/v1/query/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/.cmake/api/v1/query/client-agp/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/.cmake/api/v1/reply/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/CMakeFiles/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/CMakeFiles/CMakeTmp/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/CMakeFiles/3.22.1-g37088a8-dirty/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdC/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdC/tmp/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdCXX/
    - android/app/.cxx/Debug/1l3o35x2/arm64-v8a/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdCXX/tmp/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/.cmake/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/.cmake/api/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/.cmake/api/v1/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/.cmake/api/v1/query/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/.cmake/api/v1/query/client-agp/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/.cmake/api/v1/reply/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/CMakeFiles/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/CMakeFiles/CMakeTmp/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/CMakeFiles/3.22.1-g37088a8-dirty/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdC/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdC/tmp/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdCXX/
    - android/app/.cxx/Debug/1l3o35x2/armeabi-v7a/CMakeFiles/3.22.1-g37088a8-dirty/CompilerIdCXX/tmp/
    - android/gradle/
    - android/gradle/wrapper/
    - android/.gradle/
    - android/.gradle/vcs-1/
    - android/.gradle/8.10.2/
    - android/.gradle/8.10.2/expanded/
    - android/.gradle/8.10.2/checksums/
    - android/.gradle/8.10.2/fileHashes/
    - android/.gradle/8.10.2/fileChanges/
    - android/.gradle/8.10.2/vcsMetadata/
    - android/.gradle/8.10.2/executionHistory/
    - android/.gradle/8.10.2/dependencies-accessors/
    - android/.gradle/kotlin/
    - android/.gradle/kotlin/errors/
    - android/.gradle/kotlin/sessions/
    - android/.gradle/noVersion/
    - android/.gradle/buildOutputCleanup/
