name: challange
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/

  fonts:
  # Karla font family
  - family: Karla
    fonts:
      - asset: fonts/Karla/static/Karla-Regular.ttf
      - asset: fonts/Karla/static/Karla-Bold.ttf

  # Nunito font family
  - family: Nunito
    fonts:
      - asset: fonts/Nunito/static/Nunito-Regular.ttf
      - asset: fonts/Nunito/static/Nunito-ExtraLightItalic.ttf
